// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfnivyevvibutwtcupwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxmbml2eWV2dmlidXR3dGN1cHdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNzkxMzYsImV4cCI6MjA2NTY1NTEzNn0.pDHcIotT6FznOZNU2fOhHKj2U3mnpktCzTENXd6uJ4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);